### ISSUE TITLE
Can not fine `opencensus-service/cmd/occollector` anywhere

### ISSUE THREAD

**Issue by moooofly** [census-instrumentation/opencensus-service#108]
As README said:

> First, install the collector if you haven't.
>
> ```
> $ go get github.com/census-instrumentation/opencensus-service/cmd/occollector
> ```

But failed.

Is `occollector` still under development?

**Comment by odeke-em** [comment]
@moooofly in deed, it is still under development by another team. It'll be uploaded sometime whenever they are ready :) cc @flands

**Comment by moooofly** [comment]
Thanks for your quick response, @odeke-em

**Comment by odeke-em** [comment]
Anytime, thanks for the questions and attention @moooofly!
