### ISSUE TITLE
Stackdriver exporter configuration documentation doesn't match Golang implementation

### ISSUE THREAD

**Issue by Monkeyanator** [census-instrumentation/opencensus-service#113]
In setting up an agent, I used this to configure the Stackdriver exporter in my `config.yaml`, as per the example in the documentation: 

```
stackdriver:
  project: "your-project-id"
  enableTraces: true
```

I noticed that traces were not exporting to Stackdriver, and tried to dig in further. I found this line in `exporter/exporterparser/stackdriver.go`

`EnableTracing bool   'yaml:"enable_tracing,omitempty"'`

which doesn't match with the YAML in the documentation (`enableTraces` vs `enable_traces`). I would make a PR to match them up, but I wasn't sure if it was the docs that were out of sync or the implementation.

**Comment by songy23** [comment]
Thanks a lot for catching this @Monkeyanator. It looks like we forgot to update the parser when we changed the config name (in https://github.com/census-instrumentation/opencensus-service/commit/86437e9ee6106dd399cad7b7ba4e7391ad68c36f#diff-8caf67a7d646d4de88005ec978ab399fL6). /cc @odeke-em 

> I would make a PR to match them up, but I wasn't sure if it was the docs that were out of sync or the implementation.

I think these are out of sync - it would be great if you could send us a PR to fix :)

**Comment by Monkeyanator** [comment]
Awesome! [Created this PR](https://github.com/census-instrumentation/opencensus-service/pull/114)

**Comment by odeke-em** [comment]
Thanks for filing this issue @Monkeyanator!

We just need to update the docs or even just your own config.yaml file and not the code.
