### ISSUE TITLE
cmd/ocagent: discuss zPages sharing the same port as OCInterceptor

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#117]
Migrating here from https://github.com/census-instrumentation/opencensus-service/issues/83#issuecomment-431125662

This issue is to discuss if we should our zPages should share the same port as the OCInterceptor.

My current rationale for them not sharing that port is that local deployments of the OCInterceptor using gRPC not over TLS don't send requests with "Content-Type": "application/grpc" hence the recommended detection for multiplexing on the same port doesn't work: https://godoc.org/google.golang.org/grpc#Server.ServeHTTP

**Comment by flands** [comment]
This will be addressed in the OpenTelemetry service
