### ISSUE TITLE
all: add a git-precommit hook to ensure committed code is already compliant

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#121]
It is quite tedious to push up code, then Travis CI takes cycles to respond or cryptically fail with `go fmt` failed. In the Go project we use a git-precommit hook that checks that all files are already formatted. I think having one for this project will greatly reduce the churn with Travis and increase productivity plus wait times.

**Comment by odeke-em** [comment]
For reference here is the Go project pre-commit https://github.com/golang/go/blob/2d58fbac2f4c5c77b219e4d94b89c218ffa6f98f/misc/git/pre-commit#L1-L26

**Comment by pjanotti** [comment]
[If we enable golint](https://github.com/census-instrumentation/opencensus-service/issues/141) it should be added to the pre-commit hook too.

**Comment by flands** [comment]
This will be addressed in the OpenTelemetry Service.
