### ISSUE TITLE
performance: make a stress test harness and do some profiling

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#126]
After adding the Zipkin interceptor, I hope to release v0.0.1. It would be great to profile cmd/ocagent and bombard it with some traffic to see how well it performs but also some hotspots that we should be watching out for.

**Comment by odeke-em** [comment]
On top of normal Go processing profiling, perhaps we need to be able to analyze and visualize some behaviors like:
* Number of requests against memory usage
* Number of requests against locks acquired/released
* Throughput for the various interceptors

**Comment by flands** [comment]
Blocked by https://github.com/census-instrumentation/opencensus-service/issues/133

**Comment by songy23** [comment]
Hi all, any updates on this? I saw #133 is resolved and the load generator is available on https://github.com/Omnition/synthetic-load-generator. It would be great to document some results in this repo if we have any.

**Comment by flands** [comment]
@songy23 this is actively underway -- we hope to publish numbers by the end of this sprint

**Comment by songy23** [comment]
Great, thanks! I moved this to "In Progress" on the scrum board.

**Comment by flands** [comment]
This will be addressed in OpenTelemetry Service
