### ISSUE TITLE
cmd/occollector: bounded buffer with retry

### ISSUE THREAD

**Issue by flands** [census-instrumentation/opencensus-service#128]
The OC Collector will support the ability to send to one or more destinations (separate issue will be opened for this). Each destination needs a bounded buffer with retry capabilities. For the first version, this needs to be done at least in memory (disk can come later).

Acceptance criteria:
* Ability to have an in-memory, bounded buffer for a minimum of two destinations
* Ability to retry any failed send per destination
* Ability to configure parameters for buffer via config file

**Comment by pjanotti** [comment]
Closed via https://github.com/census-instrumentation/opencensus-service/pull/254
