### ISSUE TITLE
Consolidate Configuration for Agent and Collector

### ISSUE THREAD

**Issue by pjanotti** [census-instrumentation/opencensus-service#135]
As described in this [review comment](https://github.com/census-instrumentation/opencensus-service/pull/111#discussion_r227943295) the reading of config settings is spread in code hooking up interceptors and exportes to oc-agent. We should separate it on its own package (currently it is in oc-agent main package) and consolidate it in way that it can be used both by agent and collector so they can share the common parts of the configuration and also have a consistent means to deal with configuration in general.

**Comment by flands** [comment]
This will be addressed in the OpenTelemetry Service
