### ISSUE TITLE
receiver/zipkin: discuss or outweigh benefits of supporting v1 Thrift API

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#138]
I am coming here from https://github.com/census-instrumentation/opencensus-service/pull/111#discussion_r227851015

For maximum compatibility it would be nice to ensure that even legacy services that use the v1 Thrift API for Zipkin can still send data to our interceptor. This issue is to request a survey of services that use the v1 Thrift API, discuss any implications etc.

**Comment by odeke-em** [comment]
@basvanbeek commented in https://github.com/census-instrumentation/opencensus-service/pull/111#discussion_r228709755
>If adding anything, I'd rather see us focus on adding Zipkin protobuf support.
>
>https://github.com/openzipkin/zipkin-api/blob/master/zipkin.proto

**Comment by pjanotti** [comment]
As of today Envoy only supports Zipkin v1, unless we discover that the cost of this is really high we should do it.

**Comment by basvanbeek** [comment]
related: https://github.com/envoyproxy/envoy/issues/4839

Maybe putting effort in having Envoy support V2 would be beneficial to both projects.

**Comment by flands** [comment]
Others may be using v1 as well so would be good to support this in OC

**Comment by flands** [comment]
@odeke-em this is tagged as a discussion issue -- unless there is an objection, this is a feature definitely needed. The other issue captures the enhancement request. Other discussion/enhancement issues were handled this way -- is there a better approach?

**Comment by odeke-em** [comment]
@flands I see. I was just asking because we can transition issues from discussion by editing their titles and labels.

**Comment by adriancole** [comment]
fyi v1 json not v1 thrift. If you drop v1 thrift you won't hurt envoy.
