### ISSUE TITLE
interceptor/zipkin: consider implementing proto interception

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#154]
Suggested in a review by @basvanbeek in https://github.com/census-instrumentation/opencensus-service/pull/111#discussion_r228709755

For maximum compatibility with Zipkin services, perhaps allow intercepting proto spans.

The next question then though is:
a) What is the service being implemented, gRPC or just sending proto over HTTP or some other transport?
b) What port

We are also privileged to be able to directly ping @adriancole @basvanbeek for help with some questions.

**Comment by adriancole** [comment]
this is for zipkin a data type not a protocol, so it is the same http endpoint as json just "application/x-protobuf" instead of json content type. You'd send a ListOfSpans similar to json except proto3 https://github.com/openzipkin/zipkin-api/blob/master/zipkin.proto#L211

**Comment by odeke-em** [comment]
Awesome, thank you @adriancole for your response, that's very helpful.

**Comment by adriancole** [comment]
np we missed a spot on docs you highlighted https://github.com/openzipkin/zipkin-api/issues/56
