### ISSUE TITLE
 Deliberate decision about binary/file names

### ISSUE THREAD

**Issue by pjanotti** [census-instrumentation/opencensus-service#157]
Initially raised in a PR comment: https://github.com/census-instrumentation/opencensus-service/pull/156#discussion_r230147505

Two aspects:

1. Use of dashes instead of underscore, i.e.: `_linux` vs `-linux`

2. The name of the binaries and how we, tentatively, want people will tend to pronounce them:

ocagent_ ~ "ohkay-gent"
occollector ~ "oh-collector" or "occo-lector"

vs something like:

oc-agent ~ "oh-see-agent" or "OpenCensus agent"
oc-collector ~ "oh-see-collector" or "OpenCensus collector"

(my personal preferences: dashes and oc- prefix since it allow for future tools/services with less risky)

**Comment by flands** [comment]
This will be addressed in OpenTelemetry Service
