### ISSUE TITLE
Do not mandate a config file for agent or collector

### ISSUE THREAD

**Issue by pjanotti** [census-instrumentation/opencensus-service#158]
The agent and collector should not require a config file to start: right now it demands even an empty one. The services should use allow settings to be specified either via config file or cli.

**Comment by yurishkuro** [comment]
We're using Viper/Cobra in Jaeger. One downside I found with them is that when a binary is assembled of many components, and some components may want to register cli/config properties, the main() becomes quite verbose, so suggest investing into some simple framework to streamline the steps.

**Comment by yurishkuro** [comment]
We're using Viper/Cobra in Jaeger. One downside I found with them is that when a binary is assembled of many components, and some components may want to register cli/config properties, the main() becomes quite verbose, so suggest investing into some simple framework to streamline the steps.

**Comment by flands** [comment]
This will be addressed in OpenTelemetry Service
