### ISSUE TITLE
Rename existing *Receiver to *Sink.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-service#171]
As part of https://github.com/census-instrumentation/opencensus-service/issues/166.

Initially we named some of the internal components (in Agent-Core) `SpanReceiver` and `MetricsReceiver`. They are responsible for grouping and storing `Span`s/`Metric`s per `Node` internally. Since we decided to rename `interceptor`s to `receiver`s in https://github.com/census-instrumentation/opencensus-service/issues/166, it's better to rename the existing `receiver`s to something else, such as `sink`s.

/cc @odeke-em

**Comment by odeke-em** [comment]
Alright, I've finished https://github.com/census-instrumentation/opencensus-service/issues/166 and now I'll move onto this change too.
