### ISSUE TITLE
receiver/octrace: allow configuring limits in TraceConfig.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-service#173]
Related PR: https://github.com/census-instrumentation/opencensus-proto/pull/133.

**Comment by odeke-em** [comment]
@songy23 how is the TraceConfig related to interceptor/octrace? octrace just receives spans, doesn't do any sampling and acts like a pseudo-backend.

**Comment by songy23** [comment]
The related code is here: https://github.com/census-instrumentation/opencensus-service/blob/a763b2ee2edeb9f2a8ed73acf096b3ff458504e0/interceptor/octrace/opencensus.go#L56-L60. It's under directory interceptor/octrace. This should be updated when we split the config service out of that directory.

**Comment by odeke-em** [comment]
Ohh I see, thanks for the reference @songy23!

**Comment by flands** [comment]
@songy23 @pjanotti is this still relevant?

**Comment by songy23** [comment]
Yes `config` is still part of the trace_service RPC.

**Comment by flands** [comment]
Moved to https://github.com/open-telemetry/opentelemetry-service/issues/129
