### ISSUE TITLE
all: a bare bones agent that implements agent{Trace, Config} services

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#18]
Over the past couple of weeks we've been working on the agent service. To get things started we need to implement an agent that conforms to this proto https://github.com/census-instrumentation/opencensus-proto/tree/master/src/opencensus/proto/agent and as a gRPC service.

We've also implemented a Go exporter that already conforms to it https://github.com/census-ecosystem/opencensus-go-exporter-ocagent

**Comment by songy23** [comment]
Should this be closed now?

**Comment by odeke-em** [comment]
In deed, thank you @songy23 for the reminder. Technically only the Trace half has been implemented, as we haven't yet worked on Config's design but the issue itself was broad so this can be closed and when Config is designed, we can open a specialized issue.
