### ISSUE TITLE
PR Travis run failure: data race on TestZipkinExportersFromYAML_roundtripJSON

### ISSUE THREAD

**Issue by pjanotti** [census-instrumentation/opencensus-service#181]
This was hit during a PR Travis run but didn't repro consistently, details: https://travis-ci.org/census-instrumentation/opencensus-service/builds/452159703#L871

It is related to the buffer `buf` used with the http test server, see https://github.com/census-instrumentation/opencensus-service/blob/c99676e914a01e576f6054b038c6cc02fc9fe548/exporter/exporterparser/zipkin_test.go#L43-L49 and when it is read later at https://github.com/census-instrumentation/opencensus-service/blob/c99676e914a01e576f6054b038c6cc02fc9fe548/exporter/exporterparser/zipkin_test.go#L112-L113

**Comment by odeke-em** [comment]
Thanks for filing this @pjanotti! This race was introduced by https://github.com/census-instrumentation/opencensus-service/pull/156  particularly https://github.com/census-instrumentation/opencensus-service/pull/156/files#diff-925aacb58ff0d51b1eee965a21f0c5a4L44 which changed from a concurrent buffer to a plain buffer

The fix perhaps is to revert that part of the PR(which seemed like an unrelated change to add a Docker build) and to keep such buffers concurrency safe.

**Comment by pjanotti** [comment]
That definitely will fix the issue, but the race seems because the server is still running, so if we close it we should be good (one line clean change). The problem is that to validate my theory I need a consistent way to repro it... let me see if I can get one way to do it...

**Comment by odeke-em** [comment]
A guaranteed solution that will never race would instead to make that channel `make(chan []byte)` and inside that server do
```go
 cst := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { 
 	blob, _ := ioutil.ReadAll(r.Body)
 	r.Body.Close() 
 	responseCh <- blob
 })) 
 defer cst.Close() 
```

**Comment by odeke-em** [comment]
or a variant of it that parses even the error
```go
type reqBodyAndErr{
   body []byte
   err error
}

 buf := new(bytes.Buffer) 
 cst := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { 
 	blob, err := ioutil.ReadAll(r.Body)
 	r.Body.Close() 
 	responseCh <- &reqBodyAndErr{body: blob, err: err}
 })) 
 defer cst.Close() 
```

**Comment by pjanotti** [comment]
The last one looks good.

**Comment by pjanotti** [comment]
Per our conversation yesterday: the root of problems with this test is that the data required for the roundtrip can come in more than one call to the handler, assuming that is true none of the things that we talk about above will make the test really reliable (we wouldn't hit the data race described above but we will have other issues). In order to make the test reliable what we need a way to wait until all the data needed for the roundtrip verification is received.

**Comment by pjanotti** [comment]
A quick look at the exporter code indicates that it batches the spans and have a ticker in charge of sending the spans, so this explains why we can get the spans in separate calls. Unless there is a way to force the exporter to put the two spans used in the test in a pre-determined number of batches the test won't be reliable. I am not that familiar with the exporter options so looking only at the test itself the cheapest approach seems to send batches with a single span, then the test will work as it is.

This confirms (as expecte) that this is not product related.
