### ISSUE TITLE
Move/keep any trace translation code translation package

### ISSUE THREAD

**Issue by pjanotti** [census-instrumentation/opencensus-service#199]
Currently this is only for the Zipkin receiver but we should re-org the code to ensure that any code doing translation between trace formats (e.g.: Zipkin to OC-proto) is located under translator/trace. This helps with any reuse and perhaps in the future to serve as reference for the translations that other projects can use (should we move it under pkg?)

Side note: this is not about having a common interface for translations since the inputs are obviously different and some translations require may require different data, e.g.: http headers.

**Comment by flands** [comment]
This will be addressed in the OpenTelemetry Service
