### ISSUE TITLE
metrics/interceptor: define how the agent will be able to pull metrics from tertiary sources

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#20]
Following suit with https://github.com/census-instrumentation/opencensus-service/issues/19, we need to define how the agent will be able to pull metrics from sources like:
* Prometheus
and transform them into OpenCensus Metrics which can then be consumed/exported to the various backends. 

Basically this issue is to define the ability for the agent to be pointed to users that have all their metrics going to "System A" but are slowly doing a migration to "System B" or OpenCensus and should be able to have this done transparently without having to invasively instrument their code or take down their services. Some services like Prometheus will require us to pull from client applications while others like Stackdriver support pushing to an end point so can be intercepted.

Anyways this issue to have that discussion and set priorities and reminders for how we shall proceed.

**Comment by songy23** [comment]
Marked as P2 since we need to finalize the OpenMetrics data models first.

**Comment by odeke-em** [comment]
Alright, the metrics data model was finished as per https://github.com/census-instrumentation/opencensus-proto/pull/121 so I think this issue can now be tackled
