### ISSUE TITLE
cmd/*: orderly shutdown to minimize data loss

### ISSUE THREAD

**Issue by pjanotti** [census-instrumentation/opencensus-service#201]
In order to minimize data loss we should organize the code to perform proper shutdown: receivers 1st, then pipeline until senders. Ideally with some configurable timeout so data can be flushed etc. The goal is not to be perfect and avoid all data loss just to minimize it at a reasonable cost.

**Comment by flands** [comment]
This will be addressed in the OpenTelemetry Service.
