### ISSUE TITLE
exporter: Cleanup MultiTraceExporters

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-service#209]
MultiTraceExporters should not implement ReceiveSpans. We should have a different struct in the ocagent that implements the ReceiveSpans and forwards the spans to the MultiTraceExporters so that the MultiTraceExporters can be easily used by collector as well. This way both agent and collector can have their own specific code between receiver and exporter frameworks.

**Comment by flands** [comment]
This will be addressed in OpenTelemetry Service
