### ISSUE TITLE
exporter: consolidate YAML parsing logic

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-service#210]
Avoid duplicate code to construct the right exporters from the config:
func MultiTraceExportersFromConfig(config) TraceExporter

**Comment by odeke-em** [comment]
Am assuming this is an issue related to the exporter code duplication in cmd/ocagent and cmd/occollector for parsing exporters from YAML, right?

**Comment by bogdandrutu** [comment]
correct.

**Comment by flands** [comment]
This will be addressed in OpenTelemetry Service
