### ISSUE TITLE
receiver: consolidate YAML parsing logic

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-service#211]
Avoid duplicate code to construct the right receivers from the config:
func ReceiversFromConfig(config) TraceReceiver[]

**Comment by bogdandrutu** [comment]
Yes.

**Comment by odeke-em** [comment]
Cool, thanks! I've updated the title and I'll get this in before the week ends. /cc @pjanotti

**Comment by flands** [comment]
This will be addressed in OpenTelemetry Service
