### ISSUE TITLE
cmd: add OpenCensus metrics receiver.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-service#216]
As a follow-up of https://github.com/census-instrumentation/opencensus-service/issues/136. Currently blocked by https://github.com/census-instrumentation/opencensus-service/issues/100.

**Comment by odeke-em** [comment]
I've filed an ocagent-exporter issue that I'll mail a change for soon https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/issues/31 and concurrently we'll also need to file an issue to make metrics exporters for OpenCensus. Reusing the OpenCensus-Go stats exporters seems tempting but I suspect we might lose a bit of fidelity hence it might benefit us to just later implement our own.

**Comment by odeke-em** [comment]
Alright, I've finished the metrics ocagent-exporter which converts from OpenCensus-Go view.Data to metrics https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pull/32

Now we need to look into adding this receiver.
