### ISSUE TITLE
cmd/occollector: unable to send Zipkin traces to a Zipkin exporter

### ISSUE THREAD

**Issue by flands** [census-instrumentation/opencensus-service#231]
Steps to reproduce:

* Download the latest OC Collector
* Enable Zipkin receiver (feel free to enable debug tracer and debug logging)
* Configure Zipkin exporter

Expected: Traces would be sent to Zipkin exporter

Actual: Traces are NOT sent to Zipkin exporter and no error logs.

**Comment by pjanotti** [comment]
This is caused by https://github.com/census-instrumentation/opencensus-service/issues/232 closing this one as duplicate of it.
