### ISSUE TITLE
cmd/occollector: Add OC proto exporter

### ISSUE THREAD

**Issue by flands** [census-instrumentation/opencensus-service#251]
To send from occollector to occollector we should support exporting in OC proto format

**Comment by flands** [comment]
@pjanotti with the addition of the `opencensus` exporter this is done right? or are we missing anything?

**Comment by pjanotti** [comment]
I suspect not: we have the general issue of setting process/service info at start and not changing it plus the internal batching/timer of the default exporters. That said this should be relatively simply to add since we can rely a lot on the generated code.

**Comment by pjanotti** [comment]
Tested  OC Agent -> OC Collector using the OC exporter and it drops the service information, we will need to fix that before we can fully use it on the pipeline.

**Comment by flands** [comment]
Fixed by #337
