### ISSUE TITLE
trace/exporters: define how exporters receive traces

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#26]
We need to be able to convert traces received by the agent into exportable traces.

For the purpose of having each library being able to upload traces to the agent, currently traces received are of the trace-proto, we need to define the various trace transformers and perhaps provide protocol converters based off the data model per backend and the various protocols e.g. thrift, gRPC, HTTP. OpenCensus Go already has a bunch of exporters but transforming back to opencensus-go trace has a few limitations like attributes on Annotations being untyped https://godoc.org/go.opencensus.io/trace#Annotation but otherwise we can transform them back to OpenCensus-Go traces and perhaps it might make sense for us to reuse those already implemented exporters.

In the future, a nice to have(not important right now) would be a scheme for translating trace-proto fields to those of an exporter's backend and then we can auto-generate the clients depending on the transport type, as more backends are added.

**Comment by odeke-em** [comment]
The simplest option here would be to translate:
   `*tracepb.Span`
to
   `*trace.SpanData`
and then use all the already implemented OpenCensus-Go exporters.

Interestingly though, opencensus-agent-exporters translate from library-spanData to `*tracepb.Span` e.g. the ocagent-go-exporter translates from `*trace.SpanData` to `*tracepb.Span`.

### Synopsis
This task will be to make a translator for `*tracepb.Span` to `*trace.SpanData`

**Comment by odeke-em** [comment]
I've mailed out two PRs that provide each half of conversion

Conversion|PR
---|---
OCSpanDataToProtoSpan|https://github.com/census-instrumentation/opencensus-service/pull/35
ProtoSpanToOCSpanData|https://github.com/census-instrumentation/opencensus-service/pull/36

**Comment by songy23** [comment]
> The simplest option here would be to translate:
*tracepb.Span
to
*trace.SpanData
and then use all the already implemented OpenCensus-Go exporters.

Yes I think that's fine for the first version. In the future we may consider updating the original Go exporters so that they can accept `SpanProto` directly. That should be a user-invisible change so we can update it anytime.

**Comment by odeke-em** [comment]
>Yes I think that's fine for the first version. In the future we may consider updating the original Go exporters so that they can accept SpanProto directly. That should be a user-invisible change so we can update it anytime.

This would require us though to rewrite them which is kind of what I had talked about at the beginning of this issue but we'll instead go with the current scalable option of reusing existent exporters.

Also as https://github.com/census-instrumentation/opencensus-service/pull/35 is a noop this issue can be considered solved since we have a ProtoSpanToOCSpanData translator.
