### ISSUE TITLE
Why "opencensus" receiver but "ocagent" exporter?

### ISSUE THREAD

**Issue by flands** [census-instrumentation/opencensus-service#260]
I noticed we have an "opencensus" receiver, but an "ocagent" exporter. It is my understand per OC proto that the client library, agent and collector all support the same format. As a result, I would expect the receiver and exporter to both be called "opencensus". @odeke-em @songy23 perhaps you know the history here?

**Comment by odeke-em** [comment]
Thanks for filing this issue @flands!

It is called ocagent because of the name of the repository https://github.com/census-ecosystem/opencensus-go-exporter-ocagent but for sure let's update the exporter name to "opencensus" .

**Comment by songy23** [comment]
Agree "opencensus" is better since the exporter not only exports to agent. Will send a PR to fix.
