### ISSUE TITLE
receiver/jaeger: Jaeger Agent UDP Binary Thrift receiver fails because of dependencies

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#262]
I spent a huge chunk of time examining almost every single dependency, ripping through code trying to wonder why the Jaeger Agent wasn't successfully receiving spans on 6832 in PR #246. 

The issue found was `Bad version in ReadMessageBegin`

This issue is meant to get to the bottom of this and perhaps co-file issues with OpenCensus-Go since the Thrift compiler that was used to generate those dependencies might contribute to the problem https://github.com/census-instrumentation/opencensus-go/tree/aab39bd6a98b853ab66c8a564f5d6cfcad59ce8a/exporter/jaeger/internal/gen-go/jaeger

**Comment by yurishkuro** [comment]
If it helps, Jaeger uses different ports for binary and compact Thrift protocols
* https://github.com/jaegertracing/documentation/pull/262
* https://github.com/jaegertracing/jaeger/issues/1596

**Comment by flands** [comment]
Moved to: https://github.com/open-telemetry/opentelemetry-service/issues/128
