### ISSUE TITLE
receiver/opencensus: consider making octrace and ocmetrics internal.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-service#266]
Naming is very confusing here because there're [`opencensus.Receiver`](https://github.com/census-instrumentation/opencensus-service/blob/master/receiver/opencensus/opencensus.go#L37) as well as [`octrace.Receiver`](https://github.com/census-instrumentation/opencensus-service/blob/master/receiver/opencensus/octrace/opencensus.go#L36) and [`ocmetrics.Receiver`](https://github.com/census-instrumentation/opencensus-service/blob/master/receiver/opencensus/ocmetrics/opencensus.go#L36), but in fact they're 3 different structs that serve different purposes.

**Comment by odeke-em** [comment]
The only edit perhaps that I would recommend would be to make those "internal" to "opencensus" so
```
receiver/opencensus
        |-internal
             |- ocmetrics
             |- octrace
```

but essential ocmetrics and octrace should be awkward to use and setup that it doesn't warrant anyone using them.

**Comment by flands** [comment]
@songy23 @pjanotti is this still relevant?

**Comment by songy23** [comment]
Closing - this isn't needed for now.
