### ISSUE TITLE
cmd/ocagent: Test Jaeger and Zipkin client receivers to agent and export via opencensus

### ISSUE THREAD

**Issue by flands** [census-instrumentation/opencensus-service#273]
As we get to beta1 of the OC service, we need to ensure everything is working as expected. Given that not all client libraries support sending over opencensus proto today, the goal is to test what users of the OC service are leveraging today -- naming Zipkin (v1 and v2) as well as Jaeger (TChannel and Thrift). The oc agent will primarily be talking to the oc collector and the opencensus proto is supported for this communication.

**Comment by flands** [comment]
Zipkin v1|v2 complete -- issue found and fixed in #299 

Jaeger TODO

**Comment by sjkaris** [comment]
Tested simple jaeger locally as well. It is working. One small weirdness -- the agent did not like to export in opencensus if the endpoint was prefixed with `http` as shown in the README. Not sure why that was, but can update the readme potentially.

**Comment by pjanotti** [comment]
ocagent uses gRPC dial so the valid syntax is defined here https://github.com/grpc/grpc/blob/master/doc/naming.md I have to do some doc updates and I will cover that too.
