### ISSUE TITLE
cmd/occollector: Test receiving opencensus and exporting to Jaeger and Zipkin

### ISSUE THREAD

**Issue by flands** [census-instrumentation/opencensus-service#274]
As we get to beta1 of the OC service, we need to ensure everything is working as expected. Given that the occollector will primarily be receiving data from the ocagent, we need to ensure at least receiving over opencensus proto and exporting to common destinations such as Jaeger and ZIpkin are working.

**Comment by pjanotti** [comment]
If the collector receives OC directly from applications it gets well to Zipkin and Jaeger, however, if there is the agent between applications and the collector we lose the service information, creating traces without service information:

**Comment by pjanotti** [comment]
Similar in Zipkin:
![image](https://user-images.githubusercontent.com/5600755/50495491-4f56f780-09de-11e9-8547-561f5bac3627.png)

**Comment by pjanotti** [comment]
In order to have this working correctly we need to do https://github.com/census-instrumentation/opencensus-service/issues/251

**Comment by flands** [comment]
Zipkin done, exporting from OC collector via opencensus format not in scope for beta1.

TODO: Jaeger @pjanotti are you doing this / have done this or is @sjkaris

**Comment by pjanotti** [comment]
Sorry, I meant OC agent -> OC collector using OC requires https://github.com/census-instrumentation/opencensus-service/issues/289 not #251 - @sjkaris will be working on it per proposal on #289.
