### ISSUE TITLE
OC receiver metrics are incorrect 

### ISSUE THREAD

**Issue by pjanotti** [census-instrumentation/opencensus-service#287]
This is exposed now that the collector enabled Prometheus metrics. The issue seems external to the opencensus-service repo but creating the issue here so we can properly track it.

The gRPC metrics obtained by using `go.opencensus.io/plugin/ocgrpc` are not showing the expected data:

1. At first there are only time series for `grpc_server_method="opencensus.proto.agent.trace.v1.TraceService/Config"`. This seems to indicate that the same context may be shared for `Export` and `Config` methods.
2. If a grpc client is terminated then time series for `grpc_server_method="opencensus.proto.agent.trace.v1.TraceService/Export"` show up but it only reflects the cancellation operation, not the data actually being sent.

The bidirectional stream used by OC is not covered by ocgrpc since it responded only to connection initialization and cancellation, even after many data packages:
```
# HELP oc_collector_grpc_io_server_completed_rpcs Count of RPCs by method and status.
# TYPE oc_collector_grpc_io_server_completed_rpcs counter
oc_collector_grpc_io_server_completed_rpcs{grpc_server_method="opencensus.proto.agent.trace.v1.TraceService/Config",grpc_server_status="UNKNOWN"} 1
oc_collector_grpc_io_server_completed_rpcs{grpc_server_method="opencensus.proto.agent.trace.v1.TraceService/Export",grpc_server_status="CANCELLED"} 1
```

**Comment by pjanotti** [comment]
We should consider disabling these metrics until the issue is fully resolved, as of right now they do not provide useful data.

**Comment by pjanotti** [comment]
Removed the beta label since this is now disabled.

**Comment by flands** [comment]
This will be addressed in the OpenTelemetry Service.
