### ISSUE TITLE
opencensus format does not keep service name of span

### ISSUE THREAD

**Issue by flands** [census-instrumentation/opencensus-service#289]
The OC agent can be deployed in a variety of ways including as a binary, as a sidecar and as a daemonset. As such, the default format (opencensus) needs to work under all of this circumstances. Today, the opencensus format uses a statically defined (at start time) service name and does not respect the service name set by the span. In the case of a daemonset this means all spans come from the same service name which is undesirable.

Acceptance criteria:
* opencensus format must respect the service name of the span
* opencensus format should failback to a static service name if one is not provided

**Comment by sjkaris** [comment]
I mostly agree but feel that even (2) might not be necessary at this stage, since I don't believe sending the process/node info on each batch will be significant overhead and it simplifies the implementation a good deal.
