### ISSUE TITLE
Readme exporter/receiver inaccuracies

### ISSUE THREAD

**Issue by sjkaris** [census-instrumentation/opencensus-service#301]
First, exporters:
It seems as though the agent will not export opencensus if the endpoint has a prefix as it does in the README, so 
```yaml
  opencensus:
    endpoint: "http://localhost:10001"
```
should be
```yaml
  opencensus:
    endpoint: "localhost:10001"
```

Receivers:
Zipkin appears to only take `port` as a configuration, not address, so 
```yaml
  zipkin:
    address: "localhost:9411"
```
should be
```yaml
  zipkin:
    port: 9411
```

**Comment by pjanotti** [comment]
I started a pass on the docs and will finish this afternoon, I will double check these.
