### ISSUE TITLE
cmd/occollector: int uint16 consistency

### ISSUE THREAD

**Issue by flands** [census-instrumentation/opencensus-service#312]
--health-check-http-port int   Port on which to run the healthcheck http server. (default 13133)
      --metrics-port uint16          Port exposing collector telemetry. (default 8888)

We should use the same option for both parameters.

**Comment by pjanotti** [comment]
This was already fixed some time back in a change by @sjkaris. We need to update the help for agent/collector on next beta (not doing right now because there are pending PRs that will affect those).
