### ISSUE TITLE
Leverage DroppedAttributesCount to help users

### ISSUE THREAD

**Issue by pjanotti** [census-instrumentation/opencensus-service#319]
Client libraries can limit the number of attributes and this can be confusing to the user since some will arrive at backend. We should provide this information either as in the span itself or via log/metrics.

**Comment by maynk** [comment]
Perhaps we can inject an "opencensus collection" attribute within the span, something like __oc_java_client_dropped_attributes_count with a numeric value indicating how many attributes were dropped. We can make a config option so this is only injected when enabled.

**Comment by pjanotti** [comment]
Related link for client libraries: https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/TraceConfig.md#limits

We can't know what were the settings at the libraries so on oc service we should have higher defaults.

**Comment by flands** [comment]
This will be addressed in the OpenTelemetry Service.
