### ISSUE TITLE
vendor: either update vendored packages or remove them

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#33]
Am currently writing code to implement the OpenCensus Interceptor and "go.opencensus.io/trace" is vendored which is interrupting my tests.

We should either update these or remove them entirely and then use go modules perhaps.

**Comment by bogdandrutu** [comment]
I would suggest to remove and use go modules. Thanks.

**Comment by rakyll** [comment]
Please don't stop vendoring. Go modules support vendoring and is still the current way of having reproducible builds in Go.

**Comment by odeke-em** [comment]
>Please don't stop vendoring. Go modules support vendoring and is still the current way of having reproducible builds in Go.

In deed, I mentioned this at the beginning of this issue. I sent the first PR to remove them lest we'd have massive PRs with additions and removals. The follow-up PR is going to be for `go mod` vendorship
