### ISSUE TITLE
Configuration consolidation migration helper

### ISSUE THREAD

**Issue by pjanotti** [census-instrumentation/opencensus-service#335]
We're doing #135 and changing configuration settings. It will be great if we have something to help users migrate from old config to new one. Probably an script or helper to convert old config to new in a single step seems good enough. Silently supporting old configs in the agent and collector forces us to carry this adaptation for a long time and eventually break the compatibility.

**Comment by songy23** [comment]
Bumping this up - any updates on this?

**Comment by flands** [comment]
This will be addressed in OpenTelemetry Service
