### ISSUE TITLE
cmd/{all} make separate port from address for all receivers

### ISSUE THREAD

**Issue by pjanotti** [census-instrumentation/opencensus-service#336]
This is part of #135 to consolidate configuration.

I had a few users getting confused by the usage of "localhost:<port>" or "127.0.0.1:<port>". The issue is that typically they want to bind to all addresses on the box and specifying the host/address binds to specific address. We should separate port from host/address so for the typical case the users can just specify port.

From related go function https://godoc.org/net#Listen: “The address can use a host name, but this is not recommended, because it will create a listener for at most one of the host’s IP addresses.” Given this comment I am tempted to go just with port. That said  we can still allow host/address but in examples and docs should go with the one that should cause less confusion, just specifying port.

Binding results on my box:
```
Paulos-MBP:qtest pj$ go run netAddr.go
|            argument|                bind|
|               :9411|           [::]:9411|
|        0.0.0.0:9411|           [::]:9411|
|      localhost:9411|      127.0.0.1:9411|
|      127.0.0.1:9411|      127.0.0.1:9411|
```

```go
package main

import (
    "fmt"
    "net"
)

func main() {
    fmt.Printf("|%20s|%20v|\n", "argument", "bind")

    testAddr("tcp", ":9411")
    testAddr("tcp", "0.0.0.0:9411")
    testAddr("tcp", "localhost:9411")
    testAddr("tcp", "127.0.0.1:9411")
}

func testAddr(network, addr string) {
    l, err := net.Listen(network, addr)
    if err != nil {
        fmt.Printf("Error for %s %s: %v\n", network, addr, err)
    }
    defer l.Close()
    fmt.Printf("|%20s|%20v|\n", addr, l.Addr())
}
```

**Comment by sjkaris** [comment]
I agree with the separation and think that we should offer `port` as the main use-case in the example yamls, and allow for `hostname` as an advanced configuration that can be specified for those more advanced usecases. 

For example, the core example yaml could use:
```yaml
receivers:
  opencensus:
    port: 55678
```
and a more advanced yaml could use:
```yaml
receivers:
  opencensus:
    port: 55678
    hostname: "host.name.com"
```

**Comment by pjanotti** [comment]
@odeke-em the target here is receivers not exporters. Anyway, we should do as @sjkaris and @flands mention above and work easily for the majority of users while still supporting any special case.

**Comment by flands** [comment]
This will be addressed in OpenTelemetry Service
