### ISSUE TITLE
receiver/metrics: add Stackdriver

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#363]
There are some projects like the Go build system and many Google Cloud Platform hosted projects that use Stackdriver Metrics. Currently asking them to switch to entirely using OpenCensus might be a tough sell and requires lots of hand holding for infrastructure that was costly to write and deploy but also to take down and redeploy. However, we can give them more value proposition, give them the agent and they can then start a gradual switch after seeing the value of having their metrics be intercepted as well as their newer observability stacks using OpenCensus.

I initially worked on a design doc at https://docs.google.com/document/d/17RM-E2wRR_8LnnWgV37RAulnFAHkM1ffRt-fnIt-dbw/edit
and some CLs:
- https://go-review.googlesource.com/c/build/+/138522/
- https://go-review.googlesource.com/c/build/+/138523/

but the response from the project maintainers is that they are quite unfamiliar with OpenCensus and it will take time for them to pick it up. The agent intercepting these might be a trivial way to get folks sold on the idea

**Comment by flands** [comment]
Moving to OpenTelemetry Service
