### ISSUE TITLE
cmd/*: Reduce the number of dependencies loaded at boot up time.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-service#369]
Kind of a revisit of https://github.com/census-instrumentation/opencensus-service/pull/70 but @bogdandrutu has some new ideas on it.

**Comment by bogdandrutu** [comment]
Here, it will be good if we have all the dependencies tied together in the main function, something like:

main {
  list_of_available_receivers = ...
  list_of_available_blocks = ...
  list_of_available_exporters = ...
  ValidateConfig(list_of_available_receivers, list_of_available_blocks, list_of_available_exporters, config);
  StartAgent(list_of_available_receivers, list_of_available_blocks, list_of_available_exporters, config);
}

This way only the main.go will link all the dependencies, so people can simply re-write the main.go file and build an agent with fewer dependencies.

**Comment by songy23** [comment]
@odeke-em mentioned he has a probably simpler solution with dependency management.

**Comment by songy23** [comment]
Closing, this will be fixed with the new config.
