### ISSUE TITLE
Remove build_binaries.sh and related from the repo

### ISSUE THREAD

**Issue by pjanotti** [census-instrumentation/opencensus-service#401]
Currently there are two ways of building binaries on the repo: build_binaries.sh and via make. This is confuse and can cause the less used one to become borken. Since the CI uses make I am proposing to remove build_binaries.sh and related mention on docs. Please, let's know if there is any feature on build_binaries.sh that are needed and not available via make.

**Comment by odeke-em** [comment]
Sounds like a plan to me, thanks @pjanotti!

./build_binaries.sh should have been removed ages ago, it is just a vestige. In fact the README recommends using `make`.

**Comment by songy23** [comment]
+1 to remove build_binaries.sh.
