### ISSUE TITLE
README instructions appear incorrect

### ISSUE THREAD

**Issue by DazWilkin** [census-instrumentation/opencensus-service#445]
..and for those unfamiliar with Go Modules, it's not obvious how to proceed.

https://github.com/census-instrumentation/opencensus-service#opencensus-agent

For me:
```
go version
go version go1.12rc1 linux/amd64
```
The instruction:
```
GO111MODULE=on go get github.com/census-instrumentation/opencensus-service/cmd/ocagent
```
Results in no sources being pulled (as expected), `pkg` containing the module imports (OK) and `bin/ocagent` being generated.

There are no Makefiles so, while I don't need to `make agent`, I'm unable to `make docker-agent`.

I tried dropping the `GO111MODULE=on`, navigated to the sources but, if I then `make agent`, I get errors:
```
go: error loading module requirements
Makefile:55: recipe for target 'agent' failed
make: *** [agent] Error 1
```

I will `git clone` the repo and try that!

**Comment by songy23** [comment]
Hi @DazWilkin, please note (https://github.com/census-instrumentation/opencensus-service#usage):

> The minimum Go version required for this project is Go 1.11.4. 

This project doesn't work with Go 1.11.2 or lower versions and it's a known issue because of breaking changes in `go.sum` between Go 1.11.2- and Go 1.11.3+. We're sorry about that but I believe this is a problem with Golang.

**Comment by pjanotti** [comment]
> GO111MODULE=on go get github.com/census-instrumentation/opencensus-service/cmd/ocagent

Yes, that is wrong. I think the intention was about `go run` but then you need to clone repo or `go get` before that. 

> There are no Makefiles

There is a Makefile on the root of the repo, it should be there after proper repo clone.

Thanks for reporting! Fixing it...

**Comment by DazWilkin** [comment]
I'm using 1.12 rc1.

I wonder whether it's because I have ${GOPATH}?

Will unset that and try again

**Comment by DazWilkin** [comment]
@pjanotti Thanks! There are no Makefiles resulting from the `GO111MODULE....` command. I know there are Makefiles in the repo but they're not pulled and thus not available to me after the command.

**Comment by DazWilkin** [comment]
Unset `${GOPATH}` and `git clone` directly into `${GOPATH}/src/github.com/census-instrumentation` don't work either.

I'm able to proceed as I have the binary and can build the Docker image but... for the next victim :-)

Assume the Collector is borked too.

**Comment by pjanotti** [comment]
@DazWilkin run `go get -d github.com/census-instrumentation/opencensus-service` to clone the repo, there will be warning message about no go files on the root but after that the repo is cloned.

**Comment by pjanotti** [comment]
Clarifying `GO111MODULE=on go run ...` should work, however, `GO111MODULE=on go get ...` doesn't. Assuming that people that want to run from sources also want the repro I am adding the step to clone the repo before that (although in principle one can run without cloning the repo).

**Comment by flands** [comment]
FWIW you can grab latest release from release tab (i.e. no need to build from source).
