### ISSUE TITLE
receiver/jaeger: Support Kafka Ingester

### ISSUE THREAD

**Issue by ledor473** [census-instrumentation/opencensus-service#448]
The Jaeger Collector supports a Kafka output with 2 different encodings (`json` or `protobuf`).

It would be really nice if the OC Collector could support reading of Kafka.

I have a working but hacky implementation that uses the Jaeger Ingester (https://github.com/jaegertracing/jaeger/tree/master/cmd/ingester) and starts it here:
https://github.com/census-instrumentation/opencensus-service/blob/master/receiver/jaegerreceiver/trace_receiver.go#L173

I'm not sure how to properly implement it, but currently a boolean in the config allow to start the Ingester *or* the Agent+Collector.

**Comment by yurishkuro** [comment]
The OC Collector is supposed to sit in front of Jaeger in the ingestion pipeline. What kind of set-up are you trying to do?

**Comment by bogdandrutu** [comment]
@ledor473 I think it is good to support that, if you want to setup:

App -> OC[Agent|Collector] -> Kafka -> OC[Agent|Collector] -> One supported backend.

**Comment by bogdandrutu** [comment]
But I think @yurishkuro 's question is still valid.

**Comment by ledor473** [comment]
Ideally, the OC Collector would replace the Jaeger Collector in the Ingestion. That being said, I’m not totally sure that it’s ready to be use in production right now.

Consuming from Kafka allow us to play with the OC Collector right now without going all in.

**Comment by flands** [comment]
Moved to https://github.com/open-telemetry/opentelemetry-service/issues/122
