### ISSUE TITLE
[Datadog] Exporter configuration is incorrect

### ISSUE THREAD

**Issue by DazWilkin** [census-instrumentation/opencensus-service#454]
```
exporters:
    datadog:
        namespace: ocagent
        enable_metrics: true
        enable_tracing: false
```
So:
- metrics **enabled**
- trace **disabled**

But, when I run the agent:
```
./ocagent_linux 
{"level":"info","ts":1551468810.0261667,"caller":"config/config.go:495","msg":"Trace Exporter enabled","exporter":"datadog"}
2019/03/01 11:33:31 Running OpenCensus Trace and Metrics receivers as a gRPC service at "127.0.0.1:55678"
2019/03/01 11:33:31 Running zPages at ":55679"
```
I'm unsure how to enable metrics.

I have the Datadog statsd agent running on `:8125` but it does not appear to receive metrics through the agent using the sample code.

**Comment by flands** [comment]
Metrics is not supported in the DD exporter today: https://github.com/census-instrumentation/opencensus-service/blob/master/exporter/datadogexporter/datadog.go

**Comment by DazWilkin** [comment]
Well, that explains that then ;-)

It would be helpful to log an error if the user attempts to `enable_metrics`?

**Comment by flands** [comment]
Moved to https://github.com/open-telemetry/opentelemetry-service/issues/124
