### ISSUE TITLE
Example `ocagent.Exporter({})` does not balk if there's no agent listening

### ISSUE THREAD

**Issue by DazWilkin** [census-instrumentation/opencensus-service#455]
No agents running:
```
ss --tcp --listening \
| grep 556 \
| wc -l
0
```
But running the sample (which expects an agent on `:55678`):
https://opencensus.io/exporters/supported-exporters/go/ocagent/
```
go run main.go
#0: LineLength: 765By
#1: LineLength: 188By
#2: LineLength: 414By
#3: LineLength: 154By
#4: LineLength: 165By
Latency: 534.170ms
```
I expect the Exporter to fail when it's unable to bind to the agent's port.

Unfortunately, because the sample proceeds with impunity with|without the agent, it doesn't help debugging whether the agent is working.

**Comment by pjanotti** [comment]
This is an issue for the census-ecosystem/opencensus-go-exporter-ocagent repo, created an issue there.
