### ISSUE TITLE
opencensusexporter/stackdriver: Node should translate to unique opencensusTaskKey

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#46]
After #45 is merged, we'll have the ability to export traces proxied from multiple node but at the single exit point of the service. This issue is a placeholder to track and discuss how we'll be able to make a unique Stackdriver exporter per PID and take advantage of each Node's information.

**Comment by odeke-em** [comment]
I just suggested some code to enable this and it should be sufficient to get this working for multiplexing to nodes
```go
func (e *stackdriverKeeper) exporterForNodeLocked(node *commonpb.Node) (*stackdriver.Exporter, error) {
	langPIDKey := extractLangPIDKey(node)
	if exp, ok := e.perLangPID[langPIDKey]; ok && exp != nil {
		return exp, nil
	}

	nodeLabels := new(stackdriver.Labels)
	nodeLabels.Set("opencensus_task", langPIDKey, "Opencensus task identifier")
	// Otherwise now create the exporter
	sde, err := stackdriver.NewExporter(stackdriver.Options{
		DefaultMonitoringLabels: nodeLabels,
	})
	if err != nil {
		return nil, err
	}
	// Now memoize it
	e.perLangPID[langPIDKey] = sde
	return sde, nil
}
```

**Comment by songy23** [comment]
Note that `Node` also has information on `MonitoredResource`/resource attributes. We need a way to translate that part of information to `MonitoredResource`/resource attributes too.

**Comment by odeke-em** [comment]
>Note that Node also has information on MonitoredResource/resource attributes.

@songy23 do you mean in Node.attributes as per https://github.com/census-instrumentation/opencensus-proto/blob/df894b5863737edd0b77dade8bac59b64c4a6f98/src/opencensus/proto/agent/common/v1/common.proto#L44-L45?
or should this be in serviceInfo?

**Comment by songy23** [comment]
Yes, for now the resource metadata will be in the `map<string, string> attributes`. Note there's an ongoing discussion about resource specs: https://github.com/census-instrumentation/opencensus-specs/pull/162. Later we may want to add a dedicated message that includes the resource information.

**Comment by flands** [comment]
@songy23 is this still relevant?

**Comment by songy23** [comment]
This is already fixed - closing.
