### ISSUE TITLE
go.mod: update to latest OpenCensus-Go version as soon as release with Jaeger exporter status code setting is made

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#461]
Coming here from an issue that was filed in OpenCensus-Go https://github.com/census-instrumentation/opencensus-go/issues/1041 and for which I've mailed PR https://github.com/census-instrumentation/opencensus-go/pull/1042, this issue is a placeholder to ensure that we update OpenCensus-Go's go module version whenever that release is made.

**Comment by pjanotti** [comment]
This is already in.
