### ISSUE TITLE
receiver/mongodb: implement MongoDB data importer

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#467]
Some ~6 months ago, I made a daemon "mongostatusd" https://github.com/opencensus-integrations/mongostatusd that if given a Mongo database configuration, it'll import metrics from that database and export them to any of our view.Data exporters.

That could use a few updates like:
* Using LastValue aggregation -- when I worked on it, there wasn't a LastValue aggregation in OpenCensus-Go (or at least I hadn't yet seen it)
* Converting to OpenCensus Proto Metrics instead of Measurements aka view.Data

Perhaps we could think about to how to get this in as a receiver. I believe the value of this service would increase if folks can get metrics from their MongoDB installations without sweating, but also being able to deploy it on whatever cloud and export to a backend of their choice will be useful.

You can see the results of the first release here https://github.com/opencensus-integrations/mongostatusd/releases

**Comment by flands** [comment]
No immediate ask for this -- can be addressed in OpenTelemetry service going forward
