### ISSUE TITLE
exporter/stackdriver: allow configuration for buffer, delay, etc.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-service#474]
There're options on Go Stackdriver exporter: https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/7d76817a6490c072d4870e5097cd022cb7f66aeb/stackdriver.go#L75-L257

However those are not configurable on Agent/Collector for the moment.

**Comment by flands** [comment]
Moved to: https://github.com/open-telemetry/opentelemetry-service/issues/125
