### ISSUE TITLE
receiver/prometheus: bring in source code from Orijtech, Inc.

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-service#480]
Following suite with #478, this issue is meant to bring in code for the Prometheus receiver that I implemented and parked at Orijtech, Inc's https://github.com/orijtech/promreceiver because of issues and churn creating repositories under census-ecosystem. I'll bring it in here and then later it's final home can be decided.

**Comment by songy23** [comment]
Stale.
