### ISSUE TITLE
receiver/opencensus: fail to receive spans/metrics over RPC.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-service#502]

**Comment by odeke-em** [comment]
Hey @songy23 could you please add some more context to this issue?

**Comment by songy23** [comment]
After updating the proto gen-go files, the latest ocagent exporter cannot talk to agent or collector. (Note ocagent exporter and agent/collector both depends on oc-proto v0.2.0.)

The root cause is still unclear to me but I highly suspect it's due to the file descriptor changes with proto compiler. My guess is the RPC clients and servers generated by proto compilers in different versions don't work with each other. I've used the latest proto compiler to re-generate the go files in https://github.com/census-instrumentation/opencensus-proto/pull/195.

**Comment by odeke-em** [comment]
Yes in deed, that's the root cause but the repro is that you have Go clients that are using very stale versions of proto. I believe the correct solution is for those clients to use updated versions of `github.com/census-instrumentation/opencensus-proto/gen-go` instead of us going nuclear and making reverts here, because then that unfortunately requires reverting every single application yet the correct solution might be the simplest and that is to just get users to update their versions or just use go modules.

**Comment by songy23** [comment]
Actually the Go clients are using the same proto as agent/collector. However even both client and server use the same proto version (v0.2.0), it still doesn't work. My guess is the issue is not the proto itself, but rather the compiler that generates the go files. Previously the gen-go files were generated with protoc 3.6.1 and that may not work with some dependencies any more (likely gRPC).

**Comment by odeke-em** [comment]
>Actually the Go clients are using the same proto as agent/collector. However even both client and server use the same proto version (v0.2.0), it still doesn't work. My guess is the issue is not the proto itself, but rather the compiler that generates the go files. Previously the gen-go files were generated with protoc 3.6.1 and that may not work with some dependencies any more (likely gRPC).

To help you narrow down the problem, take a look at the tests in [receiver/opencensusreceiver/octrace/opencensus_test.go](https://github.com/census-instrumentation/opencensus-service/blob/405c9e3bc4174da7b6b82612e24a2c8645fc7fe0/receiver/opencensusreceiver/octrace/opencensus_test.go)
which pass and basically build a receiver and a literally send traces via gRPC using ocagent with the same versions of the dependencies. Those tests have been passing for all this long. Good hunch about a different protoc compiler!

I haven't looked at this code in quite a long time but I suspect perhaps an isolation of those changes might help.

**Comment by songy23** [comment]
The E2E test is skipped: https://github.com/census-instrumentation/opencensus-service/blob/405c9e3bc4174da7b6b82612e24a2c8645fc7fe0/receiver/opencensusreceiver/octrace/opencensus_test.go#L48.

A bit more thoughts: in order to get the RPC working:
1. the [proto src](https://github.com/census-instrumentation/opencensus-proto/tree/master/src) needs to be up-to-date;
2. [proto compiler](https://github.com/protocolbuffers/protobuf) needs to be be up-to-date;
3. [protoc-gen-go plug-in](https://github.com/golang/protobuf#installation) needs to be be up-to-date;
4. ocagent exporter needs to depend on the latest proto gen-go files;
5. agent/collector needs to depend on the latest proto gen-go files.

If any of these requirements went unsync, RPC will fail. In this particular case I think it's either step 2 or 3.

**Comment by odeke-em** [comment]
>The E2E test is skipped:

Right, but the other tests in there that do the same thing aren't skipped :)

Great outline and I think that might be the problem too.

**Comment by pjanotti** [comment]
Initial tests with https://github.com/grpc/grpc-go/releases/tag/v1.18.1 fixes the demo/trace. @songy23 can you check if that fixes the scenario that you discussed on gitter? If that works for that case we can close the revert and go for this one.

**Comment by songy23** [comment]
@pjanotti Unfortunately the E2E example still doesn't work, though it could also be an issue on the exporter side.

**Comment by pjanotti** [comment]
Thanks for looking @songy23 so let's go with the revert for now, later when fully understood we can move to the proper version.
