### ISSUE TITLE
Discussion: Handle data loss when Agent crashed. 

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-service#523]

**Comment by reyang** [comment]
Related to https://github.com/census-instrumentation/opencensus-specs/issues/119.

**Comment by flands** [comment]
The Service today handles this in-memory, which means on crash data is lost. While not ideal, 1) crashes are bugs that must be fixed 2) in worst case in-memory state (which is typically very small especially for agent) is lost, but new data after restart works. Long term strategy would be to introduce a disk queue. Arguably loss of this data is not mission critical. Any changes to current behavior will happen in the OpenTelemetry Service.
