### ISSUE TITLE
Set `g.co/agent` span attribute for Stackdriver exporter based library/version of node

### ISSUE THREAD

**Issue by draffensperger** [census-instrumentation/opencensus-service#525]
Currently when we convert from a `data.TraceData` structure to `go.opencensus.io/trace.Span` structures to send to actual exports in [exporterwrapper.go](https://github.com/census-instrumentation/opencensus-service/blob/c88cf9baefb4015d6d1d43e2a1f958ab8f37e067/exporter/exporterwrapper/exporterwrapper.go#L60), none of the properties from `Node` are used. See the [Node proto](https://github.com/census-instrumentation/opencensus-proto/blob/0994559fc04584b8157b89555e5e14b21bcd769d/src/opencensus/proto/agent/common/v1/common.proto#L36) for the agent.

At least for the Stackdriver exporter, we should follow the practice of the other Stackdriver exporters and write the `g.co/agent` attribute based on the `Node.LibraryInfo` that has the language and version info for the library that wrote the spans to the agent. That would allow users to understand 
what library produced the spans in a particular trace in case it needs to be upgraded.

**Comment by flands** [comment]
@draffensperger what is the latest on this?

**Comment by draffensperger** [comment]
I have some draft code for this but need to brush it off and get it out. I'll plan to work on it over the next week or so. I am aiming to get this into both the OpenCensus and OpenTelemetry services.
