### ISSUE TITLE
honeycomb exporter: basic configuration doesn't work

### ISSUE THREAD

**Issue by garthk** [census-instrumentation/opencensus-service#550]
From my reading of `README.md`, I believe `occollector_linux`  should take this `config.yaml`, accept spans on 55678, and send them to Honeycomb:

```yml
log-level: DEBUG

receivers:
  opencensus: {}

exporters:
  honeycomb:
    write_key: "XXXXXXXXXXXX"
    dataset_name: "opencensus"
```

At launch, everything seems OK. The logs, with timestamps trimmed and entries for Prometheus etc left out, suggest the receiver is running and the exporter is enabled: 
```
{"level":"info","ts":1557885940,"caller":"collector/collector.go:83","msg":"Starting...","NumCPU":2}
{"level":"info","ts":1557885940,"caller":"config/config.go:490","msg":"Trace Exporter enabled","exporter":"honeycomb"}
{"level":"info","ts":1557885941,"caller":"opencensus/receiver.go:62","msg":"OpenCensus receiver is running.","port":55678}
```

If I watch the system calls, spans are being received. `GET /metrics` on port 8888 would seem to agree that spans are being received…
```
oc_collector_oc_io_exporter_dropped_spans{oc_exporter="honeycomb",oc_receiver=""} 0
oc_collector_oc_io_exporter_received_spans{oc_exporter="honeycomb",oc_receiver=""} 1432
oc_collector_oc_io_receiver_dropped_spans{oc_receiver="oc_trace"} 0
oc_collector_oc_io_receiver_received_spans{oc_receiver="oc_trace"} 1432
```

… but I can't find any evidence spans are being sent. There's nothing in the log, despite `DEBUG`; no metrics for sending, no system calls suggesting outbound network traffic, no TCP connections known to the system, and no spans arriving at Honeycomb.

Any ideas?

**Comment by flands** [comment]
@odeke-em any idea?

**Comment by pjanotti** [comment]
Hi @garthk, OpenCensus Service doesn't have much visibility into the internals of the Honeycomb exporter. Folks at https://github.com/honeycombio/opencensus-exporter should be in a better position to help with this issue.

**Comment by akvanhar** [comment]
This should be fixed in the newest version of the honeycomb opencensus exporter if someone wouldn't mind upgrading the OC Service to use [v1.0.1](https://github.com/honeycombio/opencensus-exporter/releases/tag/v1.0.1)

**Comment by pjanotti** [comment]
@akvanhar this is just a matter of doing `go get github.com/honeycombio/opencensus-exporter@v1.0.1` - I will do it but I don't have a way to validate the change.
