### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by DavitSo** [census-instrumentation/opencensus-service#567]
launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir https://launchpad.net/~niemeyer/gocheck/trunk . in /qt_home/dsokhakyan/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exit status 3:
        bzr: ERROR: Not a branch: "http://bazaar.launchpad.net/~niemeyer/gocheck/trunk/".

**Comment by DavitSo** [comment]
could anyone help with this ?
Thanks

**Comment by inigohu** [comment]
You have to install [Bazaar](http://wiki.bazaar.canonical.com/Download) version control system

**Comment by DavitSo** [comment]
I have installed.
    /usr/bin/bzr

**Comment by DavitSo** [comment]
it doesn't work

**Comment by pjanotti** [comment]
Hi @DavitSo - I remember having issues with bzr when we running AppVeyor builds... can you provide details of your build environment? (go version, OS, ...)

**Comment by DavitSo** [comment]
Centos 7,
go version go1.11.5 linux/amd64
Bazaar (bzr) 2.5.1

**Comment by pjanotti** [comment]
no repro for me using a clean centos:7 docker image...

**Comment by songy23** [comment]
Can you try this:
```bash
$ bzr branch http://bazaar.launchpad.net/~niemeyer/gocheck/trunk/
```

Reference: https://askubuntu.com/questions/907098/error-while-cloning-source-code-of-package-bzr-error-not-a-branch?rq=1.

**Comment by DavitSo** [comment]
no , it wasn't work for me.
I'm using binaries.

**Comment by pjanotti** [comment]
@DavitSo it is hard to make progress without a repro, in lack of better alternatives can you run `go clean -modcache` and then build again?

**Comment by pjanotti** [comment]
@DavitSo I'm closing this but if you have some new info that can help us figure this out, let's know and we'll look into the issue again.
