### ISSUE TITLE
collector: jaeger exporter dropping root spans

### ISSUE THREAD

**Issue by tcolgate** [census-instrumentation/opencensus-service#593]
I'm testing opencensus service (naster ) with: 
```jaeger hotrod demo -> ocagent (jaeger-compact-thrift) -> occollector -> jaeger-collector```

In this configuration, all the intial root spans from the first web request are being dropped by occollector. They appear to contain a nil Link parent link. The entire batch of span the root span is in gets thrown away. I've dumped the links in spans from the agent, and it certainly looks like the jaeger client in hotrod is actually sending this nil link, ocagent is faithfully converting them.

**Comment by tcolgate** [comment]
#594 resolves the export, but extra work may be needed, and the links /could/ be dropped at the agent too.

**Comment by tcolgate** [comment]
I stuck a printf to dump the links  directly from the client-go in hotrod that dumps the thrift spans, and the span is definitely coming from there. The agent appears to be doing the right thing.

**Comment by pjanotti** [comment]
As you see the current implementation is very strict it doesn't accept zero or empty IDs. Did your dump show how the id was set?

**Comment by tcolgate** [comment]
It was coming out of the Jaeger reference app, so, from what I can tell,real clients in the wild are doing this. It may be more correct then to strip it at the agent?

**Comment by pjanotti** [comment]
Probably yes, but I'm trying to understand why we didn't see this before. For instance in the past we had similar issues but because the 8 byte ids were not being correctly converted to 16 byte ids in OC.

**Comment by tcolgate** [comment]
@pjanotti I think this may be the cause: https://github.com/jaegertracing/jaeger-client-go/issues/242

**Comment by dashpole** [comment]
This repository is now archived, and is succeeded by https://github.com/open-telemetry/opentelemetry-collector.
