### ISSUE TITLE
Metric Type is lost when receiving data from Java OC-Agent exporter

### ISSUE THREAD

**Issue by JonasKunz** [census-instrumentation/opencensus-service#612]
It seems like the metric type incorrectly defaults to "counter" when exposing metrics on the OC-Agent via prometheus which were received from a java OC-Agent exporter.

In the "baseline" scenario I have a java application which exposes its metrics via the Java Prometheus exporter. There the metrics look fine:
```
# HELP system_cpu_usage last value of the recent cpu usage for the whole system [cores]
# TYPE system_cpu_usage gauge
system_cpu_usage{host="5a2cfeb486de",host_address="172.27.0.9",service="config-server",} 0.11418685121107267
```

If I now switch to the Java OC-Agent exporter and enable the prometheus exporter on the OC-Agent, the metric type suddenly becomes a "counter":
```
# HELP process_cpu_usage last value of the recent cpu usage for the JVM's process [cores]
# TYPE process_cpu_usage counter
process_cpu_usage{host="5a2cfeb486de",host_address="172.27.0.9",service="config-server"} 0.017361111111111112
```

This happens to all "gauge" metrics. I assume this is a bug on the OC-Agent side, as the Java OC-Agent exporter seems to be exposing the correct metric type (according to the code).

**Comment by JonasKunz** [comment]
Accidently copied the wrong metric, here is the "system_cpu_usage" metric output by the OC-Agent:
```
# HELP system_cpu_usage last value of the recent cpu usage for the whole system [cores]
# TYPE system_cpu_usage counter
system_cpu_usage{host="532949eb4afd",host_address="172.19.0.11",service="config-server"} 1.0
```

**Comment by dashpole** [comment]
This repository is now archived, and is succeeded by https://github.com/open-telemetry/opentelemetry-collector.
