### ISSUE TITLE
Does OcAgent really behave like `Protocol Workflow`?

### ISSUE THREAD

**Issue by panzhongxian** [census-instrumentation/opencensus-service#614]
As is listed in https://github.com/census-instrumentation/opencensus-service/blob/master/DESIGN.md. 

After reading the `Export` function in octrace/opencensus.go, I am confused about following two points:

1. The agent should keep the Node as identifier. But  in octrace, the node is only use to check whether the every Export gRPC call is valid EVERYTIME. Does the **Protocol Workflow** mean that we should only set ONE time when we create an connction to OcAgent, rather than send it in every Export() grpc call?

2. Can we implement the Config() gRPC call to send TraceConfig to libary, which can be simply config in ocagent config file?

**Comment by pjanotti** [comment]
After you sent Node once you don't need to send it again unless you change any value on it. Look at this as an optimization: send node once then only send node again if it changes. For convenience you can send it every time and things will work.

You can implement the config call but at this stage the oc-agent exporter is not prepared to react to it, nor is the agent/collector.

**Comment by dashpole** [comment]
This repository is now archived, and is succeeded by https://github.com/open-telemetry/opentelemetry-collector.
