### ISSUE TITLE
Unable to use opencensus collector to post traces to backend

### ISSUE THREAD

**Issue by varungbt** [census-instrumentation/opencensus-service#615]
I have these containers running on my localhost

|CONTAINER ID       | IMAGE                                  |          PORTS               |                                                                                                       
|-------------------|:--------------------------------------:|------------------------------------------:|
|bdcc2ae9e6de       | **openzipkin/zipkin**            |               0.0.0.0:9410->9410/tcp, 0.0.0.0:9412->9411/tcp |                                                                               
|76d1831cdd5e       | **omnition/opencensus-collector:0.1.9** |         0.0.0.0:1777->1777/tcp, 0.0.0.0:8888->8888/tcp, 0.0.0.0:9411->9411/tcp, 0.0.0.0:32776->55678/tcp, 0.0.0.0:55680->55679/tcp   |
|b15c99f052c9       | **jaegertracing/all-in-one:latest**      |     0.0.0.0:5775->5775/udp, 5778/tcp, 14250/tcp, 0.0.0.0:6831->6831/udp, 14268/tcp, 6832/udp, 0.0.0.0:16686->16686/tcp          | 

Trying to directly use the opencensus collector and my collector configuration looks like this

```
#opencensus collector configuration
receivers:
  zipkin:
    address: "127.0.0.1:9411"

exporters:
  zipkin:
    endpoint: "http://127.0.0.1:9412/api/v2/spans"

```

```
package main

import (
	"log"
	"math/rand"
	"net/http"
	"strings"
	"time"

	"contrib.go.opencensus.io/exporter/zipkin"
	"go.opencensus.io/plugin/ochttp"
	"go.opencensus.io/stats/view"
	"go.opencensus.io/trace"

	openzipkin "github.com/openzipkin/zipkin-go"
	zipkinHTTP "github.com/openzipkin/zipkin-go/reporter/http"
)


func registerZipkin() {
	localEndpoint, err := openzipkin.NewEndpoint("golangsvc", "<My IP Address>:8080")
	if err != nil {
		log.Fatalf("Failed to create Zipkin exporter: %v", err)
	}
	reporter := zipkinHTTP.NewReporter**("http://localhost:9411/api/v2/spans")**
	exporter := zipkin.NewExporter(reporter, localEndpoint)
	trace.RegisterExporter(exporter)
	trace.ApplyConfig(trace.Config{DefaultSampler: trace.AlwaysSample()})
}

func main() {
	registerZipkin()
	mux := http.NewServeMux()
	mux.HandleFunc("/list", list)

	log.Printf("Server listening! ...")
	log.Fatal(http.ListenAndServe(":8080", h))
}

func list(w http.ResponseWriter, r *http.Request) {
	log.Printf("Serving request: %s", r.URL.Path)
	res := strings.Repeat("o", rand.Intn(99971)+1)
	time.Sleep(time.Duration(rand.Intn(977)+1) * time.Millisecond)
	w.Write([]byte("Hello, w" + res + "rld!"))
}

```

When I run this sample, collector logs have lots of errors

```
{"level":"info","ts":1565104219.6790097,"caller":"collector/collector.go:167","msg":"Starting...","NumCPU":2}
{"level":"info","ts":1565104219.6798325,"caller":"pprofserver/pprofserver.go:62","msg":"Starting net/http/pprof server","port":1777}
{"level":"info","ts":1565104219.6800768,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":13133,"status":"unavailable"}
{"level":"info","ts":1565104219.680858,"caller":"config/config.go:490","msg":"Trace Exporter enabled","exporter":"zipkin"}
{"level":"info","ts":1565104219.6812553,"caller":"collector/collector.go:114","msg":"Running zPages","port":55679}
{"level":"info","ts":1565104220.6819282,"caller":"opencensus/receiver.go:51","msg":"OpenCensus receiver is running.","port":55678}
{"level":"info","ts":1565104220.6824179,"caller":**"zipkin/receiver.go:50","msg":"Zipkin receiver is running.","port":9411}**
{"level":"info","ts":1565104220.6848924,"caller":"collector/telemetry.go:93","msg":"Serving Prometheus metrics","port":8888}
{"level":"info","ts":1565104220.685225,"caller":"healthcheck/handler.go:133","msg":"Health Check state change","status":"ready"}
2019/08/06 15:11:24 failed to send the request: Post http://127.0.0.1:9412/api/v2/spans: dial tcp 127.0.0.1:9412: connect: connection refused
2019/08/06 15:11:25 failed to send the request: Post http://127.0.0.1:9412/api/v2/spans: dial tcp 127.0.0.1:9412: connect: connection refused
2019/08/06 15:11:26 failed to send the request: Post http://127.0.0.1:9412/api/v2/spans: dial tcp 127.0.0.1:9412: connect: connection refused
2019/08/06 15:11:27 failed to send the request: Post http://127.0.0.1:9412/api/v2/spans: dial tcp 127.0.0.1:9412: connect: connection refused
```

I am unable to use the collector to sends the traces from it to the zipkin backend.

Also tried to use the jaeger backend , but I still see the same errors.

**Comment by varungbt** [comment]
I had a wrong opencensus collector configuration. Fixing that solved my issue.

**Comment by pjanotti** [comment]
Hi @varungbt thanks for updating the issue. Could you please point us if something was missing/unclear in the docs/config that led you to the wrong config?

**Comment by varungbt** [comment]
@pjanotti Yes I think the docs can be improved and more examples can be provided.  It would be better if the kubernetes opencensus service example can plugged with a real-time example like the hipster shop. 

Also more details on  the kubernetes deployment for the opencensus service and running the main.go to see the traces instantly should be added.

**Comment by rghetia** [comment]
I have this [PR](https://github.com/GoogleCloudPlatform/microservices-demo/pull/205) pending on making daemonset work with Istio. I hope to get this done soon.

**Comment by varungbt** [comment]
@pjanotti  @songy23  thanks. I see @rghetia PR's for the microservices demo.

I have another separate question, regarding istio.
I am currently trying to use opencensus libraries for app level stats and also use istio in the cluster.


My question is, if I just use the opencensus collector with no sidecar injected, should it be possible to export the stats to the opencensus collector from the istio envoy proxy ?

**Comment by varungbt** [comment]
@rghetia  I just thought of asking about it ..

**Comment by varungbt** [comment]
> I have this [PR](https://github.com/GoogleCloudPlatform/microservices-demo/pull/205) pending on making daemonset work with Istio. I hope to get this done soon.

@rghetia  Thanks for your reply. do you propagate all the istio headers in every trace ?

Does each of the application level trace have the istio network trace as it parent?

**Comment by rghetia** [comment]
> > I have this [PR](https://github.com/GoogleCloudPlatform/microservices-demo/pull/205) pending on making daemonset work with Istio. I hope to get this done soon.
> 
> @rghetia Thanks for your reply. do you propagate all the istio headers in every trace ?
> 
> Does each of the application level trace have the istio network trace as it parent?

There are three separate things.
1. make the hipstershop work with OcAgent (now OtelSvc) at application level.
2. Export traces/metrics from Istio (envoy proxy) to OcAgent. 
3. Tie in Istio traces with application traces i.e application span is part of the same trace as Istio originated trace.

For (1) there is the PR that I pointed earlier.
For (2) I have WIP for metrics that can receive from envoy proxy.
For (3) It needs some sort of plugin that bridges. Essentially it needs extract Trace context from request header and use that as parent.
