### ISSUE TITLE
Unable to export traces via istio envoy

### ISSUE THREAD

**Issue by varungbt** [census-instrumentation/opencensus-service#616]
I have enabled istio on my cluster and I am trying to use the opencensus service collector.
In the setup I have, the opencensus collector pod  has no sidecar injected.

The setup looks like this
[Front end container —-> istio envoy ]—-> opencensus-collector svc --> jaeger backend.

I do not see any traces exported from the istio envoy proxy to the opencensus collector svc when I try to export.
Also there are no any errors in the istio envoy or the opencensus collector pod. 

My question is, at this point of time is it possible to route traces from istio to oc-agent or oc-collector  ?

**Comment by dashpole** [comment]
This repository is now archived, and is succeeded by https://github.com/open-telemetry/opentelemetry-collector.
