### ISSUE TITLE
New release for Opencensus Agent

### ISSUE THREAD

**Issue by rghetia** [census-instrumentation/opencensus-service#617]
Agent Release 0.1.9 doesn't work on GKE+VMMetricReceiver+StackdriverExporter.
The reason is that cluster_name label is missing for k8s_container resource type. This issue is fixed in [v0.1.2](https://github.com/census-ecosystem/opencensus-go-resource/releases/tag/v0.1.2) by this [PR](https://github.com/census-ecosystem/opencensus-go-resource/pull/14).

Latest code is already using v0.1.2. Just need to release a newer version of ocagent.

**Comment by pjanotti** [comment]
Release 0.1.10 is out  https://github.com/census-instrumentation/opencensus-service/releases/tag/0.1.10

**Comment by rghetia** [comment]
@pjanotti thanks.
