### ISSUE TITLE
receiver/opencensus: Support TLS in HTTP server

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-service#623]
Currently gRPC server supports both insecure and TLS, while HTTP server only supports insecure: https://github.com/census-instrumentation/opencensus-service/blob/35b1e1c180c88c7cd5b08475fd522e10c57f406c/receiver/opencensusreceiver/opencensus.go#L254

Consider adding support for HTTP with TLS. /cc @draffensperger

**Comment by songy23** [comment]
Once this is added we'll backport it to opentelemetry-service.

**Comment by TDesai01** [comment]
Actually here, we are missing TLS support for both GRPC & HTTP Server at Opencensus. For HTTP Server TLS support is missing completely and for GRPC Server TLS support is there, but only if there is "content-type: application/grpc" or "content-type: application/grpc+proto" in request header and there is no way to set these headers in request via Opencensus Java client library.

**Comment by dashpole** [comment]
This repository is now archived, and is succeeded by https://github.com/open-telemetry/opentelemetry-collector.
