### ISSUE TITLE
Azure Monitor trace exporter prototype

### ISSUE THREAD

**Issue by ChrisCoe** [census-instrumentation/opencensus-service#626]
I am starting a new thread from #603 to keep the issue relevant. @SergeyKanzhelev I got an Azure Monitor trace exporter prototype to work with OC agent, but I do not plan on merging it as I am no longer working on this project.

**Comment by dashpole** [comment]
This repository is now archived, and is succeeded by https://github.com/open-telemetry/opentelemetry-collector.
