### ISSUE TITLE
error in prometheusreceiver

### ISSUE THREAD

**Issue by bmenasha** [census-instrumentation/opencensus-service#627]
panic: runtime error: index out of range

goroutine 178 [running]:
github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustBuckets(0xc0007cb970, 0xc000933040, 0x28, 0x28, 0xc000bf66e0, 0x14, 0x14)
	/var/lib/jenkins/workspace/src/github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal/metrics_adjuster.go:341 +0x132
github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustPoint(0xc0007cb970, 0x6, 0xc0009b0fc0, 0xc000beeb00, 0xc000a69580, 0x2121a01)
	/var/lib/jenkins/workspace/src/github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal/metrics_adjuster.go:306 +0x321
github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustPoints(0xc0007cb970, 0x6, 0xc000547200, 0x1, 0x1, 0xc00045e688, 0x1, 0x1, 0xc000546e60, 0x1, ...)
	/var/lib/jenkins/workspace/src/github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal/metrics_adjuster.go:264 +0x18a
github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustTimeseries(0xc0007cb970, 0xc000000006, 0xc000c253e0, 0xc000bfa1e0, 0xc000bd6e40, 0xc000170700)
	/var/lib/jenkins/workspace/src/github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal/metrics_adjuster.go:248 +0xbb
github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustMetricTimeseries(0xc0007cb970, 0xc00080eff0, 0xc0007cb801)
	/var/lib/jenkins/workspace/src/github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal/metrics_adjuster.go:229 +0x1c1
github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustMetric(0xc0007cb970, 0xc00080eff0, 0xc00071d001)
	/var/lib/jenkins/workspace/src/github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal/metrics_adjuster.go:214 +0x52
github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal.(*MetricsAdjuster).AdjustMetrics(0xc0007cb970, 0xc000901600, 0x11, 0x20, 0x0, 0x0, 0x0)
	/var/lib/jenkins/workspace/src/github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal/metrics_adjuster.go:192 +0x137
github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal.(*transaction).Commit(0xc0009cf200, 0x1, 0xffffffffffffffff)
	/var/lib/jenkins/workspace/src/github.com/census-instrumentation/opencensus-service/receiver/prometheusreceiver/internal/transaction.go:142 +0x1e4
github.com/prometheus/prometheus/scrape.(*scrapeLoop).append(0xc000146800, 0xc000d02000, 0x2a683, 0x3b538, 0xc0008bb960, 0x19, 0xbf663cf87175de5d, 0xccfc4ff7bd, 0x39acfc0, 0x0, ...)
	/var/lib/jenkins/go/pkg/mod/github.com/prometheus/prometheus@v0.0.0-20190131111325-62e591f928dd/scrape/scrape.go:1113 +0xa62
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc000146800, 0x37e11d600, 0x1dcd65000, 0x0)
	/var/lib/jenkins/go/pkg/mod/github.com/prometheus/prometheus@v0.0.0-20190131111325-62e591f928dd/scrape/scrape.go:833 +0x592

**Comment by dashpole** [comment]
This repository is now archived, and is succeeded by https://github.com/open-telemetry/opentelemetry-collector.

**Comment by dashpole** [comment]
This repository is now archived, and is succeeded by https://github.com/open-telemetry/opentelemetry-collector.
