### ISSUE TITLE
Instrument interceptors with OpenCensus

### ISSUE THREAD

**Issue by bogdandrutu** [census-instrumentation/opencensus-service#63]
## Trace
For trace, we start a Span every time we start a new batch (will end when we call the ReceiveSpans). Because the RPC is a bidirectional and can live long we need to decouple this span from the RPC span, but because they are related we should add the RPC span as parent link (here is a good example where links as useful).

## Stats
Measure:
* `oc.io/interceptor/received_spans` - long value

Tags:
* `opencensus_interceptor`

Measurement:
For `oc.io/interceptor/received_spans` we record a measurement every time we receive a new message from the client even if the number is 0.

Views:
We should install a distribution view with buckets {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16, 18, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100, 150, 200, 250, 300, 450, 500, 600, 700, 800, 900, 1000, 1200, 1400, 1600, 1800, 2000}

**Comment by bogdandrutu** [comment]
Please also install the ocgrpc plugin for the interceptor gRPC server.

**Comment by odeke-em** [comment]
Great suggestions @bogdandrutu! Also I think in the future(after we've finished rolling out this instrumentation), would it make sense for us to extract information from the node? For example:
* process_identifier --> "opencensus_task" for stats and perhaps service name for metrics?

**Comment by odeke-em** [comment]
>

Same thoughts, I actually have a TODO in the code as per
https://github.com/census-instrumentation/opencensus-service/blob/d91241ee30b42e86f7d439307acd3527ab544a93/interceptor/opencensus/trace_interceptor.go#L89-L91

but I think the even better way would be to create a helper method say in `internal` that creates a gRPC server for us since every interceptor that needs it will have to remember to install the ocgrpc plugin which could become error-prone.

**Comment by bogdandrutu** [comment]
@odeke-em just having a todo to also add tags from the Node is fine for the moment.

**Comment by odeke-em** [comment]
>@odeke-em just having a todo to also add tags from the Node is fine for the moment.

@bogdandrutu perfect. I've done that!

>Because the RPC is a bidirectional and can live long we need to decouple this span from the RPC span, but because they are related we should add the RPC span as parent link (here is a good example where links as useful).

Neat, so opencensus/ocgrpc has a field `IsPublicEndpoint` that does exactly this for us as per https://godoc.org/go.opencensus.io/plugin/ocgrpc#ServerHandler.IsPublicEndpoint. I'll write up a change right now and make a PR.

**Comment by odeke-em** [comment]
Alright, so with PRs:

PR|Functionality
---|---
#65|Metrics for the interceptor
#76|Tracing the OpenCensus interceptor

I believe this issue is solved. However, we'll need to keep this information and ideas in when we implement other interceptors. PTAL and feel free to reopen.

**Comment by bogdandrutu** [comment]
Maybe add a md file in the interceptor about how to instrument any interceptor.

**Comment by odeke-em** [comment]
In deed, great suggestion @bogdandrutu, I filed https://github.com/census-instrumentation/opencensus-service/issues/79.
