### ISSUE TITLE
OpenCensus Stackdriver exporter: failed to upload span: buffer full

### ISSUE THREAD

**Issue by jainbhavya65** [census-instrumentation/opencensus-service#630]
we are getting an error **OpenCensus Stackdriver exporter: failed to upload span: buffer full** in logs too many time and as we searched for the solution neither we got any flag nor any environment variable for increased buffer size. 
we are running image **omnition/opencensus-collector:0.1.11**  with stackdriver exporter

**Comment by noamhurwitz** [comment]
I am seeing this too

**Comment by gganley** [comment]
I'll report back with any findings but I found [this article](https://cloud.google.com/trace/docs/setup/go#oc-upload-fail) that seems pretty similar.

**Comment by dashpole** [comment]
This repository is now archived, and is succeeded by https://github.com/open-telemetry/opentelemetry-collector.
