### ISSUE TITLE
Doc error for starting agent

### ISSUE THREAD

**Issue by alexamies** [census-instrumentation/opencensus-service#631]
When I run the documented command to start the agent

GO111MODULE=on go run github.com/census-instrumentation/opencensus-service/cmd/ocagent --help

Given here
https://github.com/census-instrumentation/opencensus-service#agent-usage

It appears to work but is actually not listening on the port. No errors are reported but the connections are refused. But when I run it like this, it works as expected

$ cd cmd/ocagent
$ go run main.go --config /ocagent-config.yaml

**Comment by dashpole** [comment]
This repository is now archived, and is succeeded by https://github.com/open-telemetry/opentelemetry-collector.
