### ISSUE TITLE
Health Check for Agent

### ISSUE THREAD

**Issue by rpsadarangani** [census-instrumentation/opencensus-service#634]
Hello, I am trying to Opencensus Agent on Fargate as a Service, I would like to know if there is health check available for same.

**Comment by pjanotti** [comment]
@rpsadarangani IIRC the ocagent didn't have the healthcheck like the collector. Side note: I would recommend you to use the OpenTelemetry Collector instead of the OpenCensus one (of course you may have some requirements that prevent that... let's know if that is the case).

**Comment by rpsadarangani** [comment]
@pjanotti we are still waiting for OpenTelemetry to be ready for production, As it looks like it's they are still in alpha.

**Comment by pjanotti** [comment]
We have being using it in production, there are others doing the same. Notice that the "alpha warning" was removed very recently: https://github.com/open-telemetry/opentelemetry-collector/pull/562/files#diff-04c6e90faac2675aa89e2176d2eec7d8L3
