### ISSUE TITLE
metrics not properly send when restart oc-agent

### ISSUE THREAD

**Issue by yiyijin** [census-instrumentation/opencensus-service#640]
we are using oc-agent version as below, and we are running oc-agent on kubernetes environment.
```
omnition/opencensus-agent:0.1.6
```
and a problem noticed is, even when the pod is killed (so no more metrics sent by this pod), the oc-agent still keeps the old metrics, and prometheus is still getting the old metrics from oc-agent. 

It looks like restart oc-agent pod fixed the issue, however there is another problem I have seen:
when oc-agent pods restarted, it seems the pods that are sending metrics to oc-agent, oc-agent is not getting all the data. 

I just wonder is there anything I might have missed? Thanks a lot!

**Comment by dashpole** [comment]
This repository is now archived, and is succeeded by https://github.com/open-telemetry/opentelemetry-collector.
