### ISSUE TITLE
release with latest code

### ISSUE THREAD

**Issue by yiyijin** [census-instrumentation/opencensus-service#642]
Hi community, 

I noticed the latest release is on Sep 2019, we need a release that includes this [PR](https://github.com/census-instrumentation/opencensus-service/pull/637). Can you please help us build a release with latest code? Thanks a lot!

**Comment by SaschaBrechmannVHV** [comment]
@yiyijin  : This PR was included. could this Issue closed?

**Comment by dashpole** [comment]
This repository is now archived, and is succeeded by https://github.com/open-telemetry/opentelemetry-collector.
