### ISSUE TITLE
Example JSON for http/json Receiver

### ISSUE THREAD

**Issue by mc-chaos** [census-instrumentation/opencensus-service#644]
Hi everybody,

i need to check End2End my OC-Service deployment and to see if there are OC-Services with do not forward there traces.
I would use icinga "check_http" (this is just like a curl request) and make a POST to '[address]/v1/trace' with a json, as shown here [Writing with HTTP/JSON](https://github.com/census-instrumentation/opencensus-service/tree/master/receiver#writing-with-httpjson). 

But i have trouble to create a valid JSON for OC.

Could any body help me with an example JSON ?

Regards, Sascha

**Comment by dashpole** [comment]
This repository is now archived, and is succeeded by https://github.com/open-telemetry/opentelemetry-collector.
