### ISSUE TITLE
Remove images directory

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-service#72]
Go repos are not great for hosting assets. Go tools git clone repos and download the entire history. Use https://imgur.com/ or something similar to host images.

**Comment by songy23** [comment]
Let me try hosting these images on Github:

![agent-architecture](https://user-images.githubusercontent.com/10536136/46637068-6557c900-cb0f-11e8-9fbc-965af5aee080.png)
![agent-implementation](https://user-images.githubusercontent.com/10536136/46637069-65f05f80-cb0f-11e8-99e1-3cbb368e9dbc.png)
<img width="871" alt="collector-architecture" src="https://user-images.githubusercontent.com/10536136/46637070-65f05f80-cb0f-11e8-96e6-bc56468486b3.png">

**Comment by odeke-em** [comment]
I think it is too late though, they are already forever in the Git history.
