### ISSUE TITLE
Export to configured backends

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-service#8]
Define an experimental configuration format or flags and export the data from opencensusd to backends.

Note that there is a concern with this model with Prometheus because of the way Prometheus servers are sharded. Prometheus is discovering the nodes itself and this is how servers are sharded. We should be careful about not breaking this model with the exporter daemon. That's why I am suggesting us not to export a Prometheus /metrics endpoint for now.

I am suggesting to export to the following backends for now:

* Zipkin
* Datadog
* Stackdriver

**Comment by odeke-em** [comment]
@rakyll you already implemented tracing exporting to those backends and as per the new direction, we haven't yet added metrics/stats so this issue is effectively solved. Thanks for working on it!
