### ISSUE TITLE
all: test Agent and Agent-Exporter with an E2E application.

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-service#81]
As we're getting close to the initial release, we should test the real Agent implementation against the Agent Exporters with an E2E application. The [Hipster Shop](https://medium.com/@rghetia/distributed-tracing-and-monitoring-using-opencensus-fe5f6e9479fb) demo may be a good one, since it's already instrumented with OpenCensus and have several micro-services in multiple languages.

**Comment by odeke-em** [comment]
Great idea @songy23!

For Go, I've actually been doing this day 1 as per:
* https://github.com/census-instrumentation/opencensus-service/blob/master/interceptor/end_to_end_test.go#L34
* https://github.com/census-instrumentation/opencensus-service/blob/master/interceptor/opencensus/opencensus_test.go#L47

Let's in deed add an E2E app which will serve as a canonical integration.

**Comment by songy23** [comment]
Obsolete - OC-Agent has been in use in a few applications, e.g the OpenCensus interop tests, OC-PHP stats etc.
